name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: oldstable
      - name: Run unit tests
        run: go test -v ./...